### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by rlacjfjin** [dwave-examples/nurse-scheduling#10]
Hi,
When I run python nurse_scheduling.py, following error occurred:

Traceback (most recent call last):
  File "nurse_scheduling.py", line 166, in <module>
    sampler = LeapHybridSampler()
  File "/Users/jinzhe/opt/anaconda3/lib/python3.8/site-packages/dwave/system/samplers/leap_hybrid_sampler.py", line 97, in __init__
    self.client = Client.from_config(
  File "/Users/jinzhe/opt/anaconda3/lib/python3.8/site-packages/dwave/cloud/client.py", line 344, in from_config
    return _clients[_client](**config)
  File "/Users/jinzhe/opt/anaconda3/lib/python3.8/site-packages/dwave/cloud/client.py", line 386, in __init__
    raise ValueError("API token not defined")
ValueError: API token not defined

I installed dwave with pip install dwave-system.
Could you help me?
Thanks,

**Comment by hhtong** [comment]
Hi @rlacjfjin,

To use the LeapHybridSampler, you’ll need an API Token from Leap for authentication. These two articles might be helpful if you haven’t seen them yet:

- Installing Ocean Tools: https://docs.ocean.dwavesys.com/en/stable/overview/install.html
- Configuring Access to D-Wave Solvers: https://docs.ocean.dwavesys.com/en/stable/overview/sapi.html
